modLoader = "javafml"
loaderVersion = "[36,)"

license = "MIT License"
[[mods]]
modId = "torchikoma"
version = "${file.jarVersion}"
displayName = "Torchikoma"
displayURL="https://torch.dubhe.dev/"
logoFile="banner.png"
authors = "DubheStudio"
description = "A mod what about torch"

[[dependencies.torchikoma]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.torchikoma]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.torchikoma]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2,)"
ordering = "NONE"
side = "BOTH"
